---

- name: "LAMP stack using Ansible"
  become: true
  hosts: amazon
  vars_files:
    - variable.yml

  tasks:

    - name: "Installing Apache webserver"
      yum:
        name: httpd
        state: present

    - name: "Creating Apache httpd conf file"
      template:
        src: "httpd.conf.tmpl"
        dest: "/etc/httpd/conf/httpd.conf"
        owner: "root"
        group: "root"

    - name: "Restart/Enable Apache service"
      service:
        name: httpd
        state: restarted
        enabled: true
